### ISSUE TITLE
देश should be as desha? not as xeSa in examples?

### ISSUE THREAD

**Issue by CanoeFZH** [irshadbhat/python-converter-indic#1]

**Comment by irshadbhat** [comment]
could you explain why it should be so?

**Comment by CanoeFZH** [comment]
kyonki desha men de to de hai, xe men x d nahin

**Comment by irshadbhat** [comment]
I have no idea what you just said. I believe you are not familiar with WX scheme and its conversion rules. Visit https://en.wikipedia.org/wiki/WX_notation. It might help you understand why देश is written as xeSa.

**Comment by guangbaowan** [comment]
Aha. Gocha. thx.

**Comment by irshadbhat** [comment]
Also note that even though WX is a transliteration scheme, its major focus is on representing Indian Languages in Roman script without any concern about the spellings we usually follow. 

If you are looking for a such a transliteration system, you might find https://github.com/irshadbhat/indic-trans interesting.

**Comment by irshadbhat** [comment]
I am closing the issue.
